version: '3.8'
services:
  test-postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
      POSTGRES_DB: ubrc20_test
    ports:
      - "55433:5432"
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U test_user']
      interval: 5s
      timeout: 5s
      retries: 5
    # Ensure container is removed after stopping
    restart: "no" 