# Agent Communication Configuration
# This file defines the configuration for multi-agent API communication

# Default agent configuration
default_agent_config:
  timeout: 30
  retry_attempts: 3
  circuit_breaker_threshold: 5
  health_check_interval: 60  # seconds

# Agent registry
agents:
  # Example agent configurations
  brc20_indexer:
    name: "BRC-20 Indexer Agent"
    base_url: "http://localhost:8080"
    endpoints:
      - "/v1/indexer/brc20/health"
      - "/v1/indexer/brc20/list"
      - "/v1/indexer/brc20/{ticker}/info"
      - "/v1/indexer/brc20/opi/*"
    health_check_path: "/v1/indexer/brc20/health"
    timeout: 30
    retry_attempts: 3
    circuit_breaker_threshold: 5

  opi_processor:
    name: "OPI Processor Agent"
    base_url: "http://localhost:8081"
    endpoints:
      - "/v1/opi/health"
      - "/v1/opi/operations/*"
      - "/v1/opi/transactions/*"
    health_check_path: "/v1/opi/health"
    timeout: 45
    retry_attempts: 5
    circuit_breaker_threshold: 3

# Communication settings
communication:
  # Request headers
  default_headers:
    User-Agent: "AgentCommunicationService/1.0"
    Content-Type: "application/json"
    Accept: "application/json"
  
  # Retry configuration
  retry:
    backoff_factor: 2
    max_backoff: 60
    jitter: 0.1
  
  # Circuit breaker settings
  circuit_breaker:
    failure_threshold: 5
    recovery_timeout: 60
    expected_exception: "HTTPException"
  
  # Health check settings
  health_check:
    interval: 60
    timeout: 10
    failure_threshold: 3

# Logging configuration
logging:
  level: "INFO"
  format: "json"
  include_agent_id: true
  include_request_id: true

# Monitoring and metrics
monitoring:
  enabled: true
  metrics_prefix: "agent_communication"
  collect_response_times: true
  collect_error_rates: true
  collect_circuit_breaker_metrics: true

# Security settings
security:
  # Authentication (if needed)
  auth_enabled: false
  auth_type: "bearer"  # bearer, api_key, oauth2
  
  # Rate limiting
  rate_limit:
    enabled: false
    requests_per_minute: 100
  
  # SSL/TLS settings
  ssl_verify: true
  ssl_cert_path: null

# Integration examples
integrations:
  # BRC-20 token integration
  brc20_tokens:
    source_agent: "brc20_indexer"
    endpoints:
      list: "/v1/indexer/brc20/list"
      info: "/v1/indexer/brc20/{ticker}/info"
      holders: "/v1/indexer/brc20/{ticker}/holders"
      history: "/v1/indexer/brc20/{ticker}/history"
  
  # OPI operations integration
  opi_operations:
    source_agent: "opi_processor"
    endpoints:
      operations: "/v1/opi/operations/{txid}"
      block_operations: "/v1/opi/operations/block/{block_height}"
      no_return_transfers: "/v1/opi/no_return/transfers/{txid}"

# Error handling
error_handling:
  # Standard error codes
  error_codes:
    VALIDATION_ERROR: "400"
    UNAUTHORIZED: "401"
    FORBIDDEN: "403"
    NOT_FOUND: "404"
    RATE_LIMIT_EXCEEDED: "429"
    INTERNAL_ERROR: "500"
    SERVICE_UNAVAILABLE: "503"
  
  # Error response format
  error_response_format:
    error:
      code: "ERROR_CODE"
      message: "Human readable error message"
      details: {}
      timestamp: "ISO-8601 timestamp"
      agent_id: "source_agent_id"

# Development settings
development:
  # Enable debug mode
  debug: false
  
  # Mock responses for testing
  mock_responses: false
  
  # Log all requests/responses
  log_all_requests: false
  
  # Simulate network delays
  simulate_delay: false
  delay_range: [0, 100]  # milliseconds 